name: Unit tests

on:
  push:
    branches: ["**"]

concurrency:
  group: unit-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Split Tests Java
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6

      - name: Gradle check
        run: ./gradlew check

      - name: Publish test report
        uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6
        if: always()
        with:
          annotate_only: true
          detailed_summary: true
          job_name: unit-test-report
          report_paths: '**/build/test-results/test/TEST-*.xml'
